language: node_js
os: linux
node_js:
- lts/*
env:
  - LIGHTHOUSE_API_KEY=adf615154a8d49588da7f64376c841d0
before_install:
  - yarn global add npm@latest
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn install
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn lint
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - yarn lh -- --perf=90 --pwa=100 --no-comment https://
prove_v2.io.netlify.com/
branches:
  only:
    - master
    - /^greenkeeper.*$/
